### ISSUE TITLE
RealEstate-10K Training Images

### ISSUE THREAD

**Issue by alex04072000** [NagabhushanSN95/SimpleNeRF#2]
Hi, 

I noticed that the evaluation numbers on the RealEstitate-10K dataset are different from the paper.
I want to know if [this](https://github.com/NagabhushanSN95/SimpleNeRF/blob/main/src/database_utils/README.md#realestate-10k) is the issue.

If so, could you please kindly provide the GT (input/training) images you used to train the SimpleNeRF?
We want to make a fair comparison and will definitely cite your great work!
Thank you for your help in advance.

**Comment by NagabhushanSN95** [comment]
Hi, thanks for your interest in our work :)

Yes, that is the issue. I'm not sure if I can share the images on the repository (licensing issues). Can you send me a mail (my email ID is available in the paper and my personal website)? I will send you the images we used.

**Comment by alex04072000** [comment]
yulunliu@cs.nycu.edu.tw
Thank you so much for your help, @NagabhushanSN95 !
