### ISSUE TITLE
About validation

### ISSUE THREAD

**Issue by kkennethwu** [NagabhushanSN95/SimpleNeRF#4]
Hi, thanks for your great work.

I've tried the training on LLFF dataset, and modified the validation interval in demo1a config  to 10000 to do validation. There seems to be some errors on validation.

<img width="963" alt="image" src="https://github.com/NagabhushanSN95/SimpleNeRF/assets/71262989/019100d2-0d13-41e8-b2c9-1607499f499e">

**Comment by NagabhushanSN95** [comment]
Hi, thanks for your interest in our work. Yes, validation doesn't work. It's a stale code. We didn't find much use of validation and hence we haven't fixed it. Rest of the code should work fine without validation.

**Comment by kkennethwu** [comment]
Oh I see! Thank you!
